using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Security.Cryptography.X509Certificates;

/**
* @author Bluedot Innovation
* Copyright (c) 2016 Bluedot Innovation. All rights reserved.
* Update fence client demonstrates updating existing geo fences within a zone using .net http web api library
* Circular fence
* Bounding Box
* Polygonal
*/

namespace BluedotPublicApiClient.fenceclient
{
    public class BDUpdateFenceClient
    {
        private static String bdCustomerApiKey     = "bc199c80-5441-11e4-b7bb-a0481cdc3311"; //This key is generated by Bluedot Point Access UI when your account is created
        private static String bdApplicationApiKey  = "d3161e80-38d1-11e4-b039-bc305bf60831"; //This apiKey is generated when you create an application
        private static String bdZoneId             = "24d9a245-2087-421b-9972-2af2ee0970f1"; //This is the id of the zone being updated. This can be fetched by calling zones/getAll API
        private static String bdCircularFenceId    = "b4024ed6-7a28-4335-ba51-45df58459e17"; //This is the id of the fence being updated. This can be fetched by calling zones/get API
        private static String bdBoundingBoxFenceId = "b4024ed6-7a28-4335-ba51-45df58459e17"; //This is the id of the fence being updated. This can be fetched by calling zones/get API
        private static String bdPolygonalFenceId   = "b4024ed6-7a28-4335-ba51-45df58459e17"; //This is the id of the fence being updated. This can be fetched by calling zones/get API
        private static String bdGeolineFenceId     = "b4024ed6-7a28-4335-ba51-45df58459e17"; //This is the id of the fence being updated. This can be fetched by calling zones/get API

        private static String bdRestUrl = "https://api.bluedotinnovation.com/1/fences";
        
        public void updateFence()
        {
            WebRequestHandler handler = new WebRequestHandler();
            X509Certificate2 certificate = new X509Certificate2();
            handler.ClientCertificates.Add(certificate);
            HttpClient httpRestClient = new HttpClient(handler);

            //specify to use TLS 1.2 as default connection
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            httpRestClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpContent jsonFenceContent         = new StringContent(getJsonCircularFence());
            jsonFenceContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage serverResponse   = httpRestClient.PostAsync(new Uri(bdRestUrl), jsonFenceContent).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;

                Console.WriteLine("{0}", result);

            }
            else
            {
                Console.WriteLine("{0} ({1})", (int) serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }

        /*Circular fence requires a centerpoint and radius*/
        private static String getJsonCircularFence()
        {
            String circularFenceJson =
            "{" +
                "\"security\": {" +
                 "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                 "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\" " +
             "}," +
             "\"content\": {" +
                 "\"zone\": {" +
                     "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                     "\"fences\": {" +
                         "\"circles\": [" +
                             "{" +
                                 "\"fenceId\":" + "\"" + bdCircularFenceId + "\"," +
                                 "\"name\": \"Circle-1-Updated\"," +
                                 "\"color\": \"#000ffff\"," +
                                 "\"radius\": \"10.330384237225\"," +
                                 "\"center\": {" +
                                     "\"latitude\": \"-37.818326\"," +
                                     "\"longitude\": \"144.979318\" " +
                                 "}" +
                             "}" +
                         "]" +
                     "}" +
                 "}" +
             "}" +
          "}";
            return circularFenceJson;
        }

        /*Bounding box requires north east and south west points*/
        private static String getJsonBoundingBox()
        {
            String boundingBoxFenceJson =
                    "{" +
                       "\"security\": {" +
                            "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                            "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\" " +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                         "\"fences\": {" +
                            "\"rectangles\": [" +
                                "{" +
                                   "\"fenceId\":" + "\"" + bdBoundingBoxFenceId + "\"," +
                                    "\"name\": \"Bounding Box-1-Updated\"," +
                                    "\"color\": \"#3559e\"," +
                                    "\"northEast\": {" +
                                        "\"latitude\": -37.81544591805361," +
                                        "\"longitude\": 144.9786114692688" +
                                    "}," +
                                    "\"southWest\": {" +
                                        "\"latitude\": -37.81758175613945," +
                                        "\"longitude\": 144.9731397628784" +
                                    "}" +
                                "}" +
                            "]" +
                        "}" +
                    "}" +
                 "}" +
               "}";
            return boundingBoxFenceJson;
        }

        /*Polygonal fence requires a series points in lat/long*/
        private static String getJsonPolygonalFence()
        {
            String polygonalFenceJson =
                           "{" +
                               "\"security\": {" +
                                   "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                                   "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\" " +
                            "}," +
                            "\"content\": {" +
                                "\"zone\": {" +
                                    "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                                    "\"fences\": {" +
                                    "\"polygons\": [" +
                                        "{" +
                                            "\"fenceId\":" + "\"" + bdPolygonalFenceId + "\"," +
                                            "\"name\": \"Polygon-2\"," +
                                            "\"color\": \"#000ffff\"," +
                                            "\"vertices\": [" +
                                                 "{" +
                                                     "\"latitude\": -37.818717," +
                                                     "\"longitude\": 144.983085" +
                                                 "}," +
                                                 "{" +
                                                    "\"latitude\": -37.819540," +
                                                    "\"longitude\": 144.982125" +
                                                 "}," +
                                                 "{" +
                                                    "\"latitude\": -37.820298," +
                                                    "\"longitude\": 144.985178" +
                                                 "}," +
                                                 "{" +
                                                    "\"latitude\": -37.820468," +
                                                    "\"longitude\": 144.984228" +
                                                 "}," +
                                                 "{" +
                                                    "\"latitude\": -37.818768," +
                                                    "\"longitude\": 144.984330" +
                                                 "}," +
                                                 "{" +
                                                    "\"latitude\": -37.819476," +
                                                    "\"longitude\": 144.985033" +
                                                 "}," +
                                                 "{" +
                                                    "\"latitude\": -37.820527," +
                                                    "\"longitude\": 144.982978" +
                                                 "}," +
                                                 "{" +
                                                    "\"latitude\": -37.818887," +
                                                    "\"longitude\": 144.982587" +
                                                 "}" +
                                            "]" +
                                        "}" +
                                    "]" +
                                "}" +
                            "}" +
                         "}" +
                    "}";
            return polygonalFenceJson;
        }

        /*Geoline fence requires a series points in lat/long*/
        private static String getJsonGeolineFence()
        {
            String geolineFenceJson =
                           "{" +
                               "\"security\": {" +
                                   "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                                   "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\" " +
                            "}," +
                            "\"content\": {" +
                                "\"zone\": {" +
                                    "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                                    "\"fences\": {" +
                                        "\"polylines\": [" +
                                        "{" +
                                            "\"fenceId\":" + "\"" + bdGeolineFenceId + "\"," +
                                            "\"name\": \"Geoline-1\"," +
                                            "\"color\": \"#a0d7be\"," +
                                            "\"vertices\": [" +
                                                 "{" +
                                                     "\"latitude\": -37.81527640444762," +
                                                     "\"longitude\": 144.975049495697" +
                                                 "}," +
                                                 "{" +
                                                    "\"latitude\": -37.80735968553275," +
                                                    "\"longitude\": 144.9712514877319" +
                                                 "}," +
                                                 "{" +
                                                    "\"latitude\": -37.80581692842606," +
                                                    "\"longitude\": 144.9556946754456" +
                                                 "}," +
                                                  "{" +
                                                    "\"latitude\": -37.82136169906169," +
                                                    "\"longitude\": 144.9547076225281" +
                                                 "}" +
                                            "]" +
                                        "}" +
                                    "]" +
                                "}" +
                            "}" +
                         "}" +
                    "}";
            return geolineFenceJson;
        }
    }
}
