using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.Web.Script.Serialization;
using System.IO;

/**
 * @author Bluedot Innovation
 * Create Application c# client demonstrates adding an application to to an existing the customer's account using .net http web api library
 */

namespace BluedotPublicApiClient.applicationclient
{
    public class CreateApplicationWithWebhook
    {
        public void create()
        {
            String bdCustomerApiKey = "73ad7b80-7c4e-11e4-a2d3-b8ca3a6b879d"; //This key is generated by Bluedot Access UI when you register
            String bdRestUrl        = "https://api.bluedotinnovation.com/1/applications";

            String application =
               "{" +
                    "\"security\": {" +
                    /*
                      customerApiKey is generated when customer registers first time. It is also available
                      on the PointAccess interface in the Edit Profile section.
                    */
                         "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                   "}," +
                   "\"content\": { " +
                       "\"application\" : {" +
                            "\"name\" : \"A Bluedot Application\"," +
                            "\"packageName\": \"com.bluedotinnovation.testapplication\"," +
                            /* Time in Hour:Minute format.*/
                            "\"nextRuleUpdateIntervalFormatted\": \"00:07\"," +
                            "\"webhook\": {" +
                                /*The URL of the server where the webhooks will be received.*/
                                "\"url\": \"https://api.testapplication.com/webhook/checkinreceiver\"," + 
                                "\"enabled\" : true," +
                                /*The Security Token Key is the name of the field to be sent in the POST request header.*/
                                "\"securityTokenKey\" : \"authToken\"," +
                                /*The Security Token Value field is value of the Security Token Key field sent in the POST request header.*/
                                "\"securityTokenValue\" : \"f2f7a58c-f0d5-498c-9bad-acbc89923dc5\"" + 
                            "}" +
                        "}" +
                    "}" +
                "}";

            HttpClient httpRestClient = new HttpClient();
            httpRestClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpContent jsonApplicationContent         = new StringContent(@application);
            jsonApplicationContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage serverResponse         = httpRestClient.PostAsync(new Uri(bdRestUrl), jsonApplicationContent).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;
                Console.WriteLine("{0}", result);
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int) serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }
    }
}
