using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.Web.Script.Serialization;
using System.IO;
using System.Security.Cryptography.X509Certificates;

/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Create Application Zones Sync Enabled client demonstrates adding an application to your Bluedot backend 
 * using .net http web api library for which the zones sync will be available using Firebase push.
 */

namespace BluedotPublicApiClient.applicationclient
{
    public class CreateApplicationZonesSyncEnabled
    {
        public void create()
        {
            String bdCustomerApiKey = "76e1ae30-c616-11e5-a7c0-b8ca3a6b879d"; //This key is generated by Bluedot Point Access UI when your account is created
            String bdRestUrl        = "https://api.bluedotinnovation.com/1/applications";

            String applicationWithZonesSync =
               "{" +
                 "\"security\": {" +
                /*
                  customerApiKey is generated when customer registers first time. It is also available
                  on the PointAccess interface in the Edit Profile section.
                */
                         "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
               "}," +
               "\"content\": { " +
                   "\"application\" : {" +
                            "\"name\" : \"A Bluedot Application\"," +
                            "\"packageName\": \"com.bluedotinnovation.testapplication\"," +
                            /* Time in Hour:Minute format.*/
                             "\"nextRuleUpdateIntervalFormatted\": \"00:07\"," +
                            /*The Web API key from Firebase project settings. 
                            * Using this key our backend will be able to communicate with Firebase to deliver the 
                            * zones that need to be synced to your application.*/
                            "\"firebaseApiKey\": \"gDZyt1Bj_Y6S8BKyQfKH6uZ9wc475hrRlGA_6lS\"" +
                        "}" +
                   "}" +
             "}";

            WebRequestHandler handler = new WebRequestHandler();
            X509Certificate2 certificate = new X509Certificate2();
            handler.ClientCertificates.Add(certificate);
            HttpClient httpRestClient = new HttpClient(handler);

            //specify to use TLS 1.2 as default connection
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            httpRestClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpContent jsonApplicationContent = new StringContent(@applicationWithZonesSync);
            jsonApplicationContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage serverResponse         = httpRestClient.PostAsync(new Uri(bdRestUrl), jsonApplicationContent).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;
                Console.WriteLine("{0}", result);
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int) serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }
    }
}
