using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Web.Script.Serialization;
using System.Security.Cryptography.X509Certificates;

/**
* @author Bluedot Innovation
* Copyright (c) 2016 Bluedot Innovation. All rights reserved.
* Post Geofeature Sequence client demonstrates zones/sequence endpoint can be used to sequence/order the geofeatures in a Zone
* to be used for triggering the Sequential condition.
*/
namespace BluedotPublicApiClient.zoneclient
{

    public class PostGeofeaturesSequence
    {
        
        private void sequence()
        {
            String bdCustomerApiKey = "76e1ae30-c616-11e5-a7c0-b8ca3a6b879d"; //This key is generated by Bluedot Point Access UI when your account is created
            String bdApplicationApiKey = "dee11930-ebff-11e5-8e27-bc305bf60831"; //This key is generated by Bluedot Access UI when you register
            String bdZoneId = "d6c3b688-cf2e-4aac-b76b-b29f371f448e"; //This is the ID of the zone being updated.
            String[] bdSequence = { "fdf1a69b-090a-48f7-99d0-7eb631f22eac", "fbe38318-9b71-410e-98cc-10c64cdb7be4" }; //An ordered list of fence and beacon identifiers to be used for the Sequence condition.
            String bdRestUrl = "https://api.bluedotinnovation.com/1/zones/sequence";

            String zonesSequenceJson = "{" +
                "\"security\": {" +
                       "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                       "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
               "}," +
               "\"content\": {" +
                   "\"zone\": {" +
                       "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                       "\"sequence\": [ \"" + bdSequence[0] + "\",\"" + bdSequence[1] + "\"]" +
                   "}" +
               "}" +
           "}";

            WebRequestHandler handler = new WebRequestHandler();
            X509Certificate2 certificate = new X509Certificate2();
            handler.ClientCertificates.Add(certificate);
            HttpClient httpRestClient = new HttpClient(handler);

            //specify to use TLS 1.2 as default connection
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            httpRestClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpContent jsonContent = new StringContent(zonesSequenceJson);
            jsonContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage serverResponse = httpRestClient.PostAsync(new Uri(bdRestUrl), jsonContent).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;
                Console.WriteLine("{0}", result);
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int)serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }
    }
}