using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Web.Script.Serialization;
using System.Security.Cryptography.X509Certificates;

/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Update zone client demonstrates updating fields of a zone
 */

namespace BluedotPublicApiClient.zoneclient
{
    public class UpdateZone
    {
        private static String bdApplicationApiKey   = "5a9b1b78-3dd7-4f4d-8608-82408f3baf4c"; //This apiKey is generated when you create an application
        private static String bdCustomerApiKey      = "a6598740-75f5-11e4-86ca-a0481cdc3311";   //This key is generated by Bluedot Access UI when you register
        private static String bdZoneId              = "093189c3-9827-44c0-b11e-318c8c985772"; //This is the ID of the zone being updated.
        private static String bdRestUrl             = "https://api.bluedotinnovation.com/1/zones";

        public void update()
        {
            postToService(getJsonZoneTimeActive());
        }

        private void postToService(String json)
        {
            WebRequestHandler handler = new WebRequestHandler();
            X509Certificate2 certificate = new X509Certificate2();
            handler.ClientCertificates.Add(certificate);
            HttpClient httpRestClient = new HttpClient(handler);

            //specify to use TLS 1.2 as default connection
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            httpRestClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpContent jsonContent = new StringContent(json);
            jsonContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage serverResponse = httpRestClient.PostAsync(new Uri(bdRestUrl), jsonContent).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;
                Console.WriteLine("{0}", result);
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int)serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }

        /*Return JSON for a Zone which is active for a certain time period during the day. Time values have a format of HH:MM and the period value has to be one of {am/pm}*/
        private static String getJsonZoneTimeActive()
        {
            return "{" +
                "\"security\": {" +
                            "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                            "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                "}," +
                "\"content\": {" +
                    "\"zone\": {" +
                        "\"zoneId\":" + "\"" + bdZoneId + "\"" +
                        "\"zoneName\": \"First Test Bluedot Zone-Updated\"," +
                        "\"minimumRetriggerTime\": \"11:11\"," +
                        "\"enableCheckout\": true," +
                        "\"timeActive\" : {" +
                            "\"from\": {" +
                                "\"time\": \"06:00\"," +
                                "\"period\": \"am\"" +
                            "}," +
                            "\"to\": {" +
                                "\"time\": \"11:00\"," +
                                "\"period\": \"pm\"" +
                            "}" +
                        "}" +
                    "}" +
                "}" +
            "}";
        }

        /*Return JSON for a Zone which is active all day.*/
        private static String getJsonZoneActiveAllDay()
        {
            return "{" +
                    "\"security\": {" +
                            "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                            "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                "}," +
                "\"content\": {" +
                    "\"zone\": {" +
                        "\"zoneId\":" + "\"" + bdZoneId + "\"" +
                        "\"zoneName\": \"First Test Bluedot Zone-Updated\"," +
                        "\"minimumRetriggerTime\": \"11:11\"," +
                        "\"enableCheckout\": true," +
                        "\"activeAllDay\": true" +
                    "}" +
                "}" +
            "}";
        }
    }
}
