using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Web.Script.Serialization;
using System.Security.Cryptography.X509Certificates;

/**
* @author Bluedot Innovation
* Copyright (c) 2016 Bluedot Innovation. All rights reserved.
* Add Complete Zone client demonstrates adding a complete zone which has fences, beacons and actions
*/
namespace BluedotPublicApiClient.zoneclient
{

    public class CreateCompleteZone
    {
        private static String bdCustomerApiKey      = "76e1ae30-c616-11e5-a7c0-b8ca3a6b879d"; //This key is generated by Bluedot Point Access UI when your account is created
        private static String bdApplicationApiKey   = "dee11930-ebff-11e5-8e27-bc305bf60831"; //This key is generated by Bluedot Access UI when you register
        private static String bdRestUrl             = "https://api.bluedotinnovation.com/1/zones";

        public void createCompleteZoneWithTimeActive()
        {
            postToService(getJsonCompleteZoneTimeActive());
        }

        public void createCompleteZoneActiveAllDay()
        {
            postToService(getJsonCompleteZoneActiveAllDay());
        }

        private void postToService(String json)
        {
            WebRequestHandler handler = new WebRequestHandler();
            X509Certificate2 certificate = new X509Certificate2();
            handler.ClientCertificates.Add(certificate);
            HttpClient httpRestClient = new HttpClient(handler);

            //specify to use TLS 1.2 as default connection
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            httpRestClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpContent jsonContent = new StringContent(json);
            jsonContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage serverResponse = httpRestClient.PostAsync(new Uri(bdRestUrl), jsonContent).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;
                Console.WriteLine("{0}", result);
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int)serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }

        /*Return JSON for a complete Zone with a beacon and a custom action which is active for a certain time period during the day.
         * Time values have a format of HH:MM and the period value has to be one of {am/pm}*/
        private static String getJsonCompleteZoneTimeActive()
        {
            return "{" +
                    "\"security\": {" +
                            "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                            "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                "}," +
                "\"content\": {" +
                        "\"zone\": {" +
                        "\"zoneName\": \"First Test Bluedot Zone\"," +
                        "\"minimumRetriggerTime\": \"11:11\"," +
                        "\"enableCheckOut\": true," +
                        "\"timeActive\" : {" +
                            "\"from\": {" +
                                "\"time\": \"06:00\"," +
                                "\"period\": \"am\"" +
                            "}," +
                            "\"to\": {" +
                                "\"time\": \"11:00\"," +
                                "\"period\": \"pm\"" +
                            "}" +
                        "}," +
                        "\"actions\": {" +
                            "\"customActions\": [" +
                                "{" +
                                    "\"name\": \"A Custom Application action\"" +
                                "}" +
                            "]" +
                        "}," +
                        "\"beacons\": [" +
                            "{" +
                               "\"beaconId\":  \"b22ea927-f757-4a8f-8ba7-2960a4b688b2\"," +
                               "\"proximity\": 1" +
                            "}" +
                        "]" +
                    "}" +
                "}" +
            "}";
        }

        /*Return JSON for a complete Zone which is active all day with a circular geofence and a message action.*/
        private static String getJsonCompleteZoneActiveAllDay()
        {
            return "{" +
                "\"security\": {" +
                            "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                            "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                "}," +
                "\"content\": {" +
                    "\"zone\": {" +
                        "\"zoneName\": \"First Test Bluedot Zone\"," +
                        "\"minimumRetriggerTime\": \"11:11\"," +
                        "\"enableCheckOut\": true," +
                        "\"activeAllDay\": true," +
                        "\"fences\": {" +
                           "\"circles\": [" +
                               "{" +
                                   "\"name\": \"Circle-1\"," +
                                   "\"color\": \"#000ffff\"," +
                                   "\"radius\": \"30.330384237225\"," +
                                   "\"center\": {" +
                                       "\"latitude\": -37.818780," +
                                       "\"longitude\": 144.980734 " +
                                   "}" +
                               "}" +
                           "]" +
                       "}," +
                       "\"actions\": {" +
                           "\"messageActions\": [" +
                               "{" +
                                   "\"name\": \"Welcome to MCG\"," +
                                   "\"title\": \"MCG Welcome Message\"," +
                                   "\"message\": \"Welcome to MCG\"" +
                               "}" +
                           "]" +
                       "}" +
                    "}" +
                "}" +
            "}";
        }
    }
}