using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.Web.Script.Serialization;
using System.IO;
using System.Threading.Tasks;

namespace BluedotPublicApiClient.beacon
{
    class DeleteBeacon
    {
        private static String bdApplicationApiKey = "45f087e0-245c-11e4-a968-bc305bf60831"; //This apiKey is generated when you create an application
        private static String bdCustomerApiKey = "86577370-7b91-11e4-bcb7-a0481cdc3311"; //This key is generated by Bluedot Access UI when you register
        private static String beaconId = "977444dc-968a-4b13-84d8-4b194b794c18";
        private static String bdRestUrl = "http://localhost:3033/1/beacons?";


        public void delete()
        {

            bdRestUrl = bdRestUrl + "customerApiKey=" + bdCustomerApiKey + "&applicationApiKey=" + bdApplicationApiKey + "&beaconId=" + beaconId;
            HttpClient httpRestClient = new HttpClient();

            HttpResponseMessage serverResponse = httpRestClient.DeleteAsync(new Uri(bdRestUrl)).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;
                Console.WriteLine("{0}", result);
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int)serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }
    }
}
