using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.Web.Script.Serialization;
using System.IO;
using System.Threading.Tasks;


/**
* @author Bluedot Innovation
* Update beacon c# client demonstrates adding a beacon to to an existing the customer's account using net http web api library
* Pass beaconId of the beacon to update
*/

namespace BluedotPublicApiClient.beacon
{
    class UpdateBeacon
    {
        private static String bdApplicationApiKey = "45f087e0-245c-11e4-a968-bc305bf60831"; //This apiKey is generated when you create an application
        private static String bdCustomerApiKey    = "86577370-7b91-11e4-bcb7-a0481cdc3311"; //This key is generated by Bluedot Access UI when you register
        private static String bdRestUrl           = "http://localhost:3033/1/beacons";

        public void update()
        {
            HttpClient httpRestClient = new HttpClient();
            httpRestClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpContent jsonFenceContent = new StringContent(getJsonForBeacon());
            jsonFenceContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage serverResponse = httpRestClient.PostAsync(new Uri(bdRestUrl), jsonFenceContent).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;

                Console.WriteLine("{0}", result.ToString());
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int)serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }

        /*JSON to create a beacon*/
        private static String getJsonForBeacon()
        {
            String circularFenceJson =
            "{" +
                "\"security\": {" +
                 "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                 "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\" " +
             "}," +
             "\"content\": {" +
                   "\"beacon\": {" +
                             "\"beaconId\": \"977444dc-968a-4b13-84d8-4b194b794c18\"," +
                             "\"name\": \"Bluedot Offices front entrance\"," +
                             "\"proximityUuid\": \"f7826da6-4fa2-4e98-8024-bc5b71e0893e\"," +
                             "\"longitude\": \"123.34455\"," +
                             "\"latitude\": \"47.777888\"," +
                             "\"major\": 12," +
                             "\"minor\": 14," +
                             "\"macAddress\": \"23:34\"" +
                         "}" +
                  "}" +
          "}";

            return circularFenceJson;
        }
    }
}
