using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.Web.Script.Serialization;
using System.IO;
using System.Threading.Tasks;

namespace BluedotPublicApiClient.beacon
{
    class DeleteBeacon
    {
        private static String bdApplicationApiKey = "a251fbd2-5035-4887-896d-0b56abb4102d"; //This apiKey is generated when you create an application
        private static String bdCustomerApiKey = "dc67d0e0-397b-11e5-9931-0646bf53d23f"; //This key is generated by Bluedot Access UI when you register
        private static String beaconId = "b7db6f18-6557-4903-b0a7-b35b96d54fec";
        private static String bdRestUrl = "https://api.bluedotinnovation.com/1/beacons?";


        public void delete()
        {

            bdRestUrl = bdRestUrl + "customerApiKey=" + bdCustomerApiKey + "&applicationApiKey=" + bdApplicationApiKey + "&beaconId=" + beaconId;
            HttpClient httpRestClient = new HttpClient();

            HttpResponseMessage serverResponse = httpRestClient.DeleteAsync(new Uri(bdRestUrl)).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;
                Console.WriteLine("{0}", result);
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int)serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }
    }
}
