using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Web.Script.Serialization;

/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Get Beacon client demonstrates listing a beacon for a given beaconId for a customer's account from Bluedot backend.
 */
namespace BluedotPublicApiClient.beaconclient
{
    public class GetBeacon
    {
        private static String beaconId       = "b817bb5d-4b58-4f41-be5f-528fd4c7c95c"; //This is the ID of the beacon being retrieved.
        private static String customerApiKey = "ca4c8d11-6942-11e4-ba4b-a0481cdc3311"; //This key is generated by Bluedot Point Access UI when your account is created
        String bdRestUrl                     = "https://api.bluedotinnovation.com/1/beacons?customerApiKey=" + customerApiKey + "&beaconId=" + beaconId;

        public void getBeacons()
        {
            HttpClient httpRestClient = new HttpClient();

            HttpResponseMessage serverResponse = httpRestClient.GetAsync(new Uri(bdRestUrl)).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;
                Console.WriteLine("{0}", result);
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int)serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }
    }
}
