using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Security.Cryptography.X509Certificates;

/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Add Action client demonstrating adding a actions to an existing zone using net http web api libraries
 */

namespace BluedotPublicApiClient.actionclient
{

    public class CreateAllActions
    {
        private static String bdCustomerApiKey    = "bc199c80-5441-11e4-b7bb-a0481cdc3311"; //This key is generated by Bluedot Access UI when you register
        private static String bdApplicationApiKey = "d3161e80-38d1-11e4-b039-bc305bf60831"; //This apiKey is generated when you create an application
        private static String bdZoneId            = "24d9a245-2087-421b-9972-2af2ee0970f1"; //This is the id of the zone being updated. This can be fetched by calling GET Zones API
        private static String bdRestUrl           = "https://api.bluedotinnovation.com/1/actions";

        private void postToService(String json)
        {
            WebRequestHandler handler = new WebRequestHandler();
            X509Certificate2 certificate = new X509Certificate2();
            handler.ClientCertificates.Add(certificate);
            HttpClient httpRestClient = new HttpClient(handler);

            //specify to use TLS 1.2 as default connection
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            httpRestClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpContent jsonContent            = new StringContent(json);
            jsonContent.Headers.ContentType    = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage serverResponse = httpRestClient.PostAsync(new Uri(bdRestUrl), jsonContent).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;
                Console.WriteLine("{0}", result);
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int) serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }
        public void addAllAction()
        {
            postToService(getJsonAllAction());
        }

        /*JSON Format for a URL action*/
        private static String getJsonAllAction()
        {
            String allActionJson =
                 "{" +
                    "\"security\": {" +
                        "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                        "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                            "\"actions\": {" +
                                "\"customActions\": [" +
                                    "{" +
                                        "\"name\": \"A Custom Application action\"" +
                                    "}" +
                                "]," +
                                "\"soundActions\": [" +
                                    "{" +
                                        "\"name\": \"A Sound action\"" +
                                    "}" +
                                "]," +
                                "\"vibrationActions\": [" +
                                    "{" +
                                        "\"name\": \"A Vibration action\"" +
                                    "}" +
                                "]," +
                                "\"urlActions\": [" +
                                    "{" +
                                        "\"name\": \"Bluedot URL\"," +
                                        "\"url\": \"http://www.bluedotinnovation.com\"" +
                                    "}" +
                                "]," +
                                "\"messageActions\": [" +
                                    "{" +
                                        "\"name\": \"Welcome to Bluedot Innovation\"," +
                                        "\"title\": \"Welcome to Bluedot Innovation Message\"," +
                                        "\"message\": \"Welcome to Bluedot Innovation.\"" +
                                    "}" +
                                "]" +
                            "}" +
                        "}" +
                    "}" +
                "}";
            return allActionJson;
        }
    }

}
