using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Security.Cryptography.X509Certificates;

/**
 * @author Bluedot Innovation
 * Copyright (c) 2016 Bluedot Innovation. All rights reserved.
 * Add Action with conditions client demonstrates adding an action with different types of conditions to an existing zone 
 * using .net http web api libray
 */

namespace BluedotPublicApiClient.actionclient
{
    public class CreateActionWithCondition
    {
        private static String bdCustomerApiKey    = "a6598740-75f5-11e4-86ca-a0481cdc3311"; //This key is generated by Bluedot Point Access UI when your account is created.
        private static String bdApplicationApiKey = "5a9b1b78-3dd7-4f4d-8608-82408f3baf4c"; //This apiKey is generated when you create an application
        private static String bdZoneId            = "b80e50eb-b9f9-4ed5-966e-4b2e39cc0549"; //This is the id of the zone being updated. This can be fetched by calling GET Zones API
        private static String bdRestUrl           = "https://api.bluedotinnovation.com/1/actions";

        private void postToService(String json)
        {
            WebRequestHandler handler = new WebRequestHandler();
            X509Certificate2 certificate = new X509Certificate2();
            handler.ClientCertificates.Add(certificate);
            HttpClient httpRestClient = new HttpClient(handler);

            //specify to use TLS 1.2 as default connection
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

            httpRestClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpContent jsonContent = new StringContent(json);
            jsonContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage serverResponse = httpRestClient.PostAsync(new Uri(bdRestUrl), jsonContent).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;

                Console.WriteLine("{0}", result);
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int)serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }

        public void addPercenatgeCrossedCondition()
        {
            postToService(getJsonActionWithPercentageCrossedCondition());
        }

        public void addSequentialCondition()
        {
            postToService(getJsonActionWithSequentialCondition());
        }

        public void addDateRangeCondition()
        {
            postToService(getJsonActionWithDateRangeCondition());
        }

        public void addTimeActiveCondition()
        {
            postToService(getJsonActionWithTimeActiveCondition());
        }

        public void addBearingCondition()
        {
            postToService(getJsonActionWithBearingCondition());
        }

        public void addSpeedCondition()
        {
            postToService(getJsonActionWithSpeedCondition());
        }

        /* Example of Custom Action with Percentage Crossed condition. */
        private static String getJsonActionWithPercentageCrossedCondition()
        {

            String customActionWithPercentageCrossedCondtionJson =
                 "{" +
                    "\"security\": {" +
                        "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                        "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                            "\"actions\": {" +
                            "\"customActions\": [" +
                                "{" +
                                    "\"name\": \"A Custom Action with Percentage Crossed Condition\"," +
                                    "\"conditions\": {" +
                                       "\"percentageCrossed\": [" +
                                          "{" +
                                              "\"percentage\": 90," +
                                              "\"timeoutPeriod\": \"00:15\"" +
                                           "}" +
                                      "]" +
                                   "}" +
                                "}" +
                            "]" +
                          "}" +
                        "}" +
                    "}" +
                "}";
            return customActionWithPercentageCrossedCondtionJson;
        }

        /* Example of Custom Action with Sequential condition. */
        private static String getJsonActionWithSequentialCondition()
        {

            String customActionWithSequentialCondtionJson =
                 "{" +
                    "\"security\": {" +
                        "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                        "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                            "\"actions\": {" +
                            "\"customActions\": [" +
                                "{" +
                                    "\"name\": \"A Custom Action with a Sequential Percentage Crossed Condition\"," +
                                    "\"conditions\": {" +
                                       "\"percentageCrossed\": [" +
                                          "{" +
                                              "\"percentage\": 90," +
                                              "\"timeoutPeriod\": \"00:15\"," +
                                              "\"sequential\": true" +
                                           "}" +
                                      "]" +
                                   "}" +
                                "}" +
                            "]" +
                          "}" +
                        "}" +
                    "}" +
                "}";
            return customActionWithSequentialCondtionJson;
        }

        /* Example of Custom Action with Date Range condition. */
        private static String getJsonActionWithDateRangeCondition()
        {

            String customActionWithDateRangeCondtionJson =
                 "{" +
                    "\"security\": {" +
                        "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                        "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                            "\"actions\": {" +
                            "\"customActions\": [" +
                                "{" +
                                    "\"name\": \"A Custom Action with a Date Condition\"," +
                                    "\"conditions\": {" +
                                    "\"dateRange\": [" +
                                        "{" +
                                            "\"start\": \"10/11/2016\"," +
                                            "\"end\": \"26/12/2017\"" +
                                        "}" +
                                    "]" +
                                   "}" +
                                "}" +
                            "]" +
                          "}" +
                        "}" +
                    "}" +
                "}";
            return customActionWithDateRangeCondtionJson;
        }

        /* Example of Custom Action with Time Active condition. */
        private static String getJsonActionWithTimeActiveCondition()
        {

            String customActionWithTimeActiveCondtionJson =
                 "{" +
                    "\"security\": {" +
                        "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                        "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                            "\"actions\": {" +
                            "\"customActions\": [" +
                                "{" +
                                    "\"name\": \"A Custom Action with a Time Condition\"," +
                                    "\"conditions\": {" +
                                        "\"timeActive\": [{" +
                                            "\"from\": {" +
                                                "\"time\": \"06:01\"," +
                                                "\"period\": \"am\" " +
                                            "}," +
                                            "\"to\": {" +
                                                "\"time\": \"11:00\"," +
                                                "\"period\": \"pm\" " +
                                            "}" +
                                        "}]" +
                                   "}" +
                                "}" +
                            "]" +
                          "}" +
                        "}" +
                    "}" +
                "}";
            return customActionWithTimeActiveCondtionJson;
        }

        /* Example of Custom Action with Bearing condition. */
        private static String getJsonActionWithBearingCondition()
        {

            String customActionWithBearingCondtionJson =
                 "{" +
                    "\"security\": {" +
                        "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                        "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                            "\"actions\": {" +
                            "\"customActions\": [" +
                                "{" +
                                    "\"name\": \"A Custom Action with a Time Condition\"," +
                                    "\"conditions\": {" +
                                    "\"bearing\": [" +
                                        "{" +
                                            "\"fromAngle\": 0," +
                                            "\"toAngle\": 90" +
                                        "}" +
                                    "]" +
                                   "}" +
                                "}" +
                            "]" +
                          "}" +
                        "}" +
                    "}" +
                "}";
            return customActionWithBearingCondtionJson;
        }

        /* Example of Custom Action with Speed condition. */
        private static String getJsonActionWithSpeedCondition()
        {

            String customActionWithSpeedCondtionJson =
                 "{" +
                    "\"security\": {" +
                        "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                        "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                            "\"actions\": {" +
                            "\"customActions\": [" +
                                "{" +
                                    "\"name\": \"A Custom Action with a Time Condition\"," +
                                    "\"conditions\": {" +
                                    "\"speed\": [" +
                                        "{" +
                                            "\"minmumSpeed\": 10," +
                                            "\"maximumSpeed\": 20" +
                                        "}" +
                                    "]" +
                                   "}" +
                                "}" +
                            "]" +
                          "}" +
                        "}" +
                    "}" +
                "}";
            return customActionWithSpeedCondtionJson;
        }

    }
}
