using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using System.Threading.Tasks;

/**
 * @author Bluedot Innovation
 * Add Action REST client demonstrating adding a actions to an existing zone using net http web api libraries
 */

namespace BluedotPublicApiClient.zoneclient
{

    public class CreateAllActions
    {
        private static String bdCustomerApiKey    = "bc199c80-5441-11e4-b7bb-a0481cdc3311"; //This key is generated by Bluedot Access UI when you register
        private static String bdApplicationApiKey = "d3161e80-38d1-11e4-b039-bc305bf60831"; //This apiKey is generated when you create an application
        private static String bdRestUrl           = "https://api.bluedotinnovation.com/1/actions";
        private static String bdZoneId            = "24d9a245-2087-421b-9972-2af2ee0970f1"; //This is the id of the zone being updated. This can be fetched by calling zones/getAll API
   

        private void postToService(String json)
        {
            HttpClient httpRestClient = new HttpClient();
            httpRestClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            HttpContent jsonContent            = new StringContent(json);
            jsonContent.Headers.ContentType    = new MediaTypeHeaderValue("application/json");

            HttpResponseMessage serverResponse = httpRestClient.PostAsync(new Uri(bdRestUrl), jsonContent).Result;
            if (serverResponse.IsSuccessStatusCode)
            {
                var result = serverResponse.Content.ReadAsStringAsync().Result;
                Console.WriteLine("{0}", result);
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int) serverResponse.StatusCode, serverResponse.Content.ReadAsStringAsync().Result);
            }
        }
        public void addURLAction()
        {
            postToService(getJsonUrlAction());
        }

        public void addMessageAction()
        {
            postToService(getJsonMessageAction());
        }

        public void addVibrationAction()
        {
            postToService(getJsonVibrationAction());
        }

        public void addApplicationAction()
        {
            postToService(getJsonApplicationAction());
        }

        public void addSoundAction()
        {

        }

        /*JSON Format for a URL action*/
        private static String getJsonUrlAction()
        {
            String urlActionJson =
                 "{" +
                    "\"security\": {" +
                        "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                        "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                            "\"actions\": {" +
                                "\"urlActions\": [" +
                                    "{" +
                                        "\"name\": \"Bluedot URL\"," +
                                        "\"url\": \"http://www.bluedotinnovation.com\"" +
                                    "}" +
                                "]" +
                            "}" +
                        "}" +
                    "}" +
                "}";
            return urlActionJson;
        }

        /*JSON Format for a Vibration action*/
        private static String getJsonVibrationAction()
        {
            String urlActionJson =
                 "{" +
                    "\"security\": {" +
                        "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                        "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                            "\"actions\": {" +
                                "\"vibrationActions\": [" +
                                    "{" +
                                        "\"name\": \"A vibration action\"" +
                                    "}" +
                                "]" +
                            "}" +
                        "}" +
                    "}" +
                "}";
            return urlActionJson;
        }

        /*JSON Format for an application action*/
        private static String getJsonApplicationAction()
        {
            String applicationActionJson =
                 "{" +
                    "\"security\": {" +
                        "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                        "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                            "\"actions\": {" +
                                "\"customActions\": [" +
                                    "{" +
                                        "\"name\": \"A Custom Application action\"" +
                                    "}" +
                                "]" +
                            "}" +
                        "}" +
                    "}" +
                "}";
            return applicationActionJson;
        }

        /*JSON Format for a Message action*/
        private static String getJsonMessageAction()
        {
            String messageActionJson =
                 "{" +
                    "\"security\": {" +
                        "\"apiKey\":" + "\"" + bdApplicationApiKey + "\"," +
                        "\"customerApiKey\":" + "\"" + bdCustomerApiKey + "\"" +
                    "}," +
                    "\"content\": {" +
                        "\"zone\": {" +
                            "\"zoneId\":" + "\"" + bdZoneId + "\"," +
                            "\"actions\": {" +
                                "\"messageActions\": [" +
                                    "{" +
                                        "\"name\": \"Welcome to MCG\"," +
                                        "\"title\": \"MCG Welcome Message\"," +
                                        "\"message\": \"Welcome to MCG\"" +
                                    "}" +
                                "]" +
                            "}" +
                        "}" +
                    "}" +
                "}";
            return messageActionJson;
        }

    }

}
